name: Run Event Data Ingestion
on:
  push:
    branches: [develop]
  # schedule:
  #   - cron: '0 20 * * 2,4'

jobs:
  run-ingestion:
    runs-on: ubuntu-latest
    env:
      API_KEY: ${{ secrets.API_KEY }}
      BASE_URL: ${{ secrets.BASE_URL }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PW: ${{ secrets.DB_PW }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}

    steps:
      - name: Checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner.

      - name: List files
        run: |
          pwd
          ls -a
      
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.10

      - name: Upgrade pip to latest version
        run: pip install --upgrade pip

      - name: Install pipenv
        run: pip install pipenv

      - name: Install Pipfile dependencies
        run: pipenv install 
      
      - name: Execute run_event_import.py
        run: |
          pipenv run python3 run_event_import.py
          
  test-schedule:
    runs-on: ubuntu-latest
    steps:
      - name: not on Tuesday and Thursday
        if: github.event.schedule != '0 20 * * 2,4'
        run: |
          echo 'Not on Tuesday Thursday schedule.'
