name: Run Event Data Ingestion
on:
  push:
    branches: [main, develop, feature/*]
  schedule:
    - cron: '0 0 * * 2,4'

jobs:
  run-ingestion:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner.
      
      - name: Decode Base64 secrets (dev)
        if: github.ref == 'refs/heads/develop' || contains(github.ref, 'refs/heads/feature/')
        run: echo $TESTING_DB_CONTENT | base64 -d > .env
        env:
          TESTING_DB_CONTENT: ${{ secrets.TESTING_DB_CONTENT }}

      - name: Decode Base64 secrets (prod)
        if: github.ref == 'refs/heads/main'
        run: echo $PROD_DB_CONTENT | base64 -d > .env
        env:
          PROD_DB_CONTENT: ${{ secrets.PROD_DB_CONTENT }}

      - name: List files
        run: |
          pwd
          ls -a
      
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.10

      - name: Upgrade pip to latest version
        run: pip install --upgrade pip

      - name: Install pipenv
        run: |
          pip install pipenv

      - name: Install Pipfile dependencies
        run: |
          pipenv install 
      
      - name: Execute phoenix_relentless_beats.py
        run: |
          pipenv run python3 ingestion/phoenix_relentless_beats.py
      
      - name: Execute los_angeles_sound_nightclub.py
        run: |
          pipenv run python3 ingestion/los_angeles_sound_nightclub.py
          
  test-schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Not triggered on scheduled daily 12am run
        if: github.event.schedule != '0 0 * * 2,4'
        run: |
          echo 'Did not execute on scheduled Tuesday or Thursday 12am run'
